workflow:
  rules:
    # Build commits on main
    - if: '$CI_COMMIT_BRANCH == "main"'
    # Build merge requests
    - if: $CI_MERGE_REQUEST_ID
    # Build tagged commits
    - if: $CI_COMMIT_TAG

default:
  image: node:18-alpine
  tags:
    - docker

cache: &global_cache
  key:
    files:
      - package-lock.json
  policy: pull
  paths:
    - node_modules/

stages:
  - Prepare
  - Build

Install:
  stage: Prepare
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - npm install

Lint:
  stage: Build
  script:
    - npm run lint

TypeCheck:
  stage: Build
  script:
    - npm run type-check
  allow_failure: true # TODO: Remove this when all types are fixed.

Build:
  stage: Build
  script:
    - npm run build
